title: Services

columns:
  - width: 1/3
    # In the first column, we reuse the `notes` section
    # (defined in `/site/blueprints/sections/notes.yml` twice with different page status and headline
    sections:
      drafts:
        extends: sections/services
        label: Drafts
        status: draft

      unlisted:
        extends: sections/services
        label: In Review
        status: unlisted

  - width: 2/3
    # In the second column, we reuse the same section, this time for listed pages and with a different headline
    sections:
      listed:
        extends: sections/services
        label: Published
        status: listed
        size: small
        layout: list

